version: '3.8'
services:
    db:
        image: postgres:13.1
        environment:
            - POSTGRES_USER=$DB_USER
            - POSTGRES_PASSWORD=$DB_PASSWORD
            - POSTGRES_DB=$DB_NAME
        ports:
            - $DB_PORT:$DB_PORT
        volumes:
            - ./db/data:/var/lib/postgresql/data
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        restart: always
        command: -p $DB_PORT

    api:
        depends_on:
            - db
        build: ./api
        environment:
            - NODE_ENV=$API_NODE_ENV
            - PORT=$API_PORT
            - PGHOST=db
            - PGPORT=$DB_PORT
            - PGUSER=$DB_USER
            - PGPASSWORD=$DB_PASSWORD
            - PGDATABASE=$DB_NAME
        ports:
            - $API_PORT:$API_PORT
        volumes:
            - ./api:/app
            - /app/node_modules
    ocene:
        build: ./ocene
        environment:
            - NODE_ENV=$UI_NODE_ENV
            - PORT=$UI_PORT
            - REACT_APP_API_HOST
        ports:
            - $UI_PORT:$UI_PORT
        volumes:
            - ./ocene:/app
            - /app/node_modules
        stdin_open: true

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
    go-multi:
        build: ./go-multistage
        ports:
            - $GO_PORT:$GO_PORT
