apiVersion: apps/v1
kind: Deployment
metadata:
    name: client2-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            component: web2
    template:
        metadata:
            labels:
                component: web2
        spec:
            containers:
                - name: client
                  image: boneb/ocene:dark
                  ports:
                      - containerPort: 3000
