apiVersion: v1
kind: Service
metadata:
    labels:
        app: hello
    name: hello
spec:
    ports:
        - port: 8081
          protocol: TCP
          targetPort: 8081
    selector:
        app: hello
    type: ClusterIP
