apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: hello
    name: hello
spec:
    replicas: 3
    selector:
        matchLabels:
            app: hello
    strategy:
        rollingUpdate:
            maxSurge: 0
            maxUnavailable: 1
        type: RollingUpdate
    minReadySeconds: 15
    template:
        metadata:
            labels:
                app: hello
                version: v3
        spec:
            containers:
                - image: boneb/go_multi:read
                  imagePullPolicy: IfNotPresent
                  name: hello
                  ports:
                      - containerPort: 8081
                  readinessProbe:
                      httpGet:
                          path: /ready
                          port: 8081
                      initialDelaySeconds: 15
                      periodSeconds: 5
                  livenessProbe:
                      httpGet:
                          path: /live
                          port: 8081
                      initialDelaySeconds: 15
                      periodSeconds: 5
            restartPolicy: Always
            terminationGracePeriodSeconds: 30
